# Lab 2

### Part 1

In [5]:
from EigenClass import EigenClass
import numpy as np

matrix = np.array([
  [-1, 0, 0],
  [1, 4, 4],
  [-1, -2, -2]
])

print(EigenClass.get_eigen(matrix)[1])


1: [0. 0. 0.] == [ 0.  0. -0.]
2: [ 0.         -1.78885438  0.89442719] == [ 0.         -1.78885438  0.89442719]
3: [-0.57735027  0.57735027 -0.57735027] == [-0.57735027  0.57735027 -0.57735027]
[[ 0.          0.          0.57735027]
 [ 0.70710678 -0.89442719 -0.57735027]
 [-0.70710678  0.4472136   0.57735027]]
